name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3
        
        # Setup Node.js
      - name: Set up NODEJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'
        
        # Install NodeJS dependencies with NPM
      - name: Install NodeJS dependencies with npm
        run: npm install

        # SonarQube Analysis
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        # Docker Image Build
      - name: Build Docker Image
        run: docker build -t $GITHUB_SHA .

        # Scan Docker Image with Trivy
      - name: Trivy Scan
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image $GITHUB_SHA

        # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          
        # Login to AmazonECR
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI}}
