name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3
        
        # Setup Node.js
      - name: Set up NODEJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'
        
        # Install NodeJS dependencies with NPM
      - name: Install NodeJS dependencies with npm
        run: npm install

        # SonarQube Analysis
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


        
