name: CI/CD Pipeline

on:
  push:
    branches:
      - main


  pull_request:
    branches:
      - main

job:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout code
        uses: actions/checkout@v3
